[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# iced = "0.9.0"
websocket = "0.26.5"
configparser = "3.0.2"
env_logger = "0.10.0"
log="0.4.19"